### ISSUE TITLE
登陆时验证码一直验证失败

### ISSUE THREAD

**Issue by java-war** [Jiiiiiin/jiiiiiin-security#8]
2019-01-17 11:53:13.457  INFO 6664 --- [nio-9090-exec-1] c.j.s.c.v.c.i.ImageValidateCodeGenerator : 图形验证码 76xx 有效期 120
2019-01-17 11:53:24.287  INFO 6664 --- [nio-9090-exec-3] c.j.s.c.v.code.ValidateCodeFilter        : 校验请求(/mng/authentication/form)中的验证码,验证码类型IMAGE
2019-01-17 11:53:42.565  INFO 6664 --- [nio-9090-exec-2] c.j.s.c.v.c.i.ImageValidateCodeGenerator : 图形验证码 fbwx 有效期 120
2019-01-17 11:55:00.652 ERROR 6664 --- [nio-9090-exec-3] c.j.s.c.v.code.ValidateCodeFilter        : 验证码校验失败

cn.jiiiiiin.security.core.validate.code.ValidateCodeException: 验证码不存在
	at cn.jiiiiiin.security.core.validate.code.impl.AbstractValidateCodeProcessor.validate(AbstractValidateCodeProcessor.java:117) ~[classes/:na]
	at cn.jiiiiiin.security.core.validate.code.ValidateCodeFilter.doFilterInternal(ValidateCodeFilter.java:123) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-4.2.7.RELEASE.jar:4.

**Comment by Jiiiiiin** [comment]
你可以检查一下验证码是否是调用`SessionValidateCodeRepository#save`被存储到session中，验证码有效期设置：
`final int expireIn = ServletRequestUtils.getIntParameter(request.getRequest(), SecurityConstants.DEFAULT_PARAMETER_NAME_EXPIRE_IN, securityProperties.getValidate().getImageCode().getExpireIn());`
有两种方式，1.通配置 2.通过参数，单位为秒；

另外存储介质应该是`SessionValidateCodeRepository`这个bean： #4 

你可以调试一下，或者参考[Spring Security开发安全的REST服务](https://coding.imooc.com/class/134.html)中关于验证码的对应章节

**Comment by kaiccc** [comment]
Hi，我也遇到了这个问题。错误内容一致。根据 你的描述，我查看了一下代码，`SessionValidateCodeRepository#save` 将session 、验证码存入到了redis 缓存中
但是在 做验证码校验的时候，通过  `SessionValidateCodeRepository#get` 获取不到验证码。
难道是 通过 request 生成 SessionStrategy  与获取验证码的 session 不一致？
都是我本机操作的呀。
我通过客户端 查看到 redis 中有数据的。
对 `SessionStrategy` 刚刚接触，不太熟悉，求指教。
代码是 master 分支。

**Comment by Jiiiiiin** [comment]
@kaiccc 不应该存储在redis中呀。呵呵

`AbstractValidateCodeProcessor#validateCodeRepository`这个bean，应该使用的是:
![](https://ws3.sinaimg.cn/large/006tNc79gy1fz9pbawjzlj31ge08e0t6.jpg)

不知道你们为什么会弄到了redis中？我说的是验证码。

**Comment by kaiccc** [comment]
.env.development文件下：VUE_APP_SEVER_URL=http://127.0.0.1:9090

npm run serve
其他没动

**Comment by Jiiiiiin** [comment]
肯定不对呀，这个要配置成真实的WIFI 映射出来的局域网IP地址

**Comment by Jiiiiiin** [comment]
9000

**Comment by Jiiiiiin** [comment]
@java-war @kaiccc

**Comment by java-war** [comment]
# 开发环境

# 页面 title 前缀
VUE_APP_TITLE=jiiiiiin-security内管

# 后台的url
#VUE_APP_SEVER_URL=http://192.168.3.43:9000
VUE_APP_SEVER_URL=http://127.0.0.1:9000

没用，跟踪进去过，存验证码后立即再取的时候是有，但在验证时去取就发现取不到了。

**Comment by kaiccc** [comment]
master 分支，只修改了这些。




![_2019-01-18_10-03-38](https://user-images.githubusercontent.com/19568707/51360851-574f1680-1b08-11e9-823a-ae806c74e032.jpg)
![_2019-01-18_10-03-32](https://user-images.githubusercontent.com/19568707/51360857-5a4a0700-1b08-11e9-9888-9ffb02ff8a41.jpg)
![_2019-01-18_09-58-38](https://user-images.githubusercontent.com/19568707/51360861-5ddd8e00-1b08-11e9-8080-80e5cf390cd2.jpg)

**Comment by Jiiiiiin** [comment]
好的 我晚点试试

**Comment by Jiiiiiin** [comment]
如果你的前后端都是正常启动的话，（redis 没有报错：(error) DENIED Redis is running in protected mode because protected mode is enabled），那么，就应该没有问题，我特地重新检出了项目测试过了，你在重新更新一下项目看吧
另外我从检出master分支到启动项目，登录做相关交易，录制了一个视频，发到这里：https://youtu.be/eemHJEvsTog  你可以看看

**Comment by mengyou658** [comment]
插一句话，获取验证码的链接没有携带cookies，所以不是同一个session，访问127.0.0.1:9000则会携带cookies

**Comment by Jiiiiiin** [comment]
@java-war @kaiccc @mengyou658 请查看 #15
